<?xml version='1.0' encoding='UTF-8' ?>
<testsuite name="com.feri.redmedalertandroidapp.data.integrationTest.LocalDataIntegrationTest" tests="2" failures="1" errors="0" skipped="0" time="5.335" timestamp="2025-01-08T18:01:18" hostname="localhost">
  <properties>
    <property name="device" value="Pixel_6a_Edited_API_34(AVD) - 14" />
    <property name="flavor" value="" />
    <property name="project" value=":app" />
  </properties>
  <testcase name="testClearData" classname="com.feri.redmedalertandroidapp.data.integrationTest.LocalDataIntegrationTest" time="4.005" />
  <testcase name="testLocalDataStorage" classname="com.feri.redmedalertandroidapp.data.integrationTest.LocalDataIntegrationTest" time="0.043">
    <failure>java.util.concurrent.RejectedExecutionException: Task com.feri.redmedalertandroidapp.data.DataRepository$$ExternalSyntheticLambda1&#64;71d5afa rejected from java.util.concurrent.ThreadPoolExecutor&#64;83a0925[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 6]
at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2082)
at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:842)
at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1374)
at com.feri.redmedalertandroidapp.data.DataRepository.clearAllData(DataRepository.java:92)
at com.feri.redmedalertandroidapp.data.integrationTest.LocalDataIntegrationTest.cleanup(LocalDataIntegrationTest.java:42)
</failure>
  </testcase>
</testsuite>